/*
 * MIT License
 *
 * Copyright (c) 2024 kiyasui-hito
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

%{
#define YYDEBUG 1

#include "lex.yy.c"
#include <stdio.h>

void yyerror(char* msg);

%}

%error-verbose

%token KOI_SCRIPT_TOKEN_TYPE_UNRECOGNIZED 257
%token KOI_SCRIPT_TOKEN_TYPE_INVALID 258
%token KOI_SCRIPT_TOKEN_TYPE_MIN 259
%token KOI_SCRIPT_TOKEN_TYPE_VAR 260
%token KOI_SCRIPT_TOKEN_TYPE_FUNC 261
%token KOI_SCRIPT_TOKEN_TYPE_CLASS 262
%token KOI_SCRIPT_TOKEN_TYPE_LIBRARY 263
%token KOI_SCRIPT_TOKEN_TYPE_IDENTIFIER 264
%token KOI_SCRIPT_TOKEN_TYPE_SEPARATOR 265
%token KOI_SCRIPT_TOKEN_TYPE_DELIMITER 266
%token KOI_SCRIPT_TOKEN_TYPE_CLASS_OBJECT 267
%token KOI_SCRIPT_TOKEN_TYPE_CLASS_BOOL 268
%token KOI_SCRIPT_TOKEN_TYPE_CLASS_CHAR 269
%token KOI_SCRIPT_TOKEN_TYPE_CLASS_NUMBER 270
%token KOI_SCRIPT_TOKEN_TYPE_CLASS_INT 271
%token KOI_SCRIPT_TOKEN_TYPE_CLASS_UINT 272
%token KOI_SCRIPT_TOKEN_TYPE_CLASS_FLOAT 273
%token KOI_SCRIPT_TOKEN_TYPE_CLASS_UFLOAT 274
%token KOI_SCRIPT_TOKEN_TYPE_CLASS_STRING 275
%token KOI_SCRIPT_TOKEN_TYPE_CLASS_TYPE_NAME 276
%token KOI_SCRIPT_TOKEN_TYPE_NULL_LITERAL 277
%token KOI_SCRIPT_TOKEN_TYPE_BOOL_FALSE_LITERAL 278
%token KOI_SCRIPT_TOKEN_TYPE_BOOL_TRUE_LITERAL 279
%token KOI_SCRIPT_TOKEN_TYPE_CHAR_LITERAL 280
%token KOI_SCRIPT_TOKEN_TYPE_INT_LITERAL 281
%token KOI_SCRIPT_TOKEN_TYPE_UINT_LITERAL 282
%token KOI_SCRIPT_TOKEN_TYPE_FLOAT_LITERAL 283
%token KOI_SCRIPT_TOKEN_TYPE_UFLOAT_LITERAL 284
%token KOI_SCRIPT_TOKEN_TYPE_STRING_LITERAL 285
%token KOI_SCRIPT_TOKEN_TYPE_GROUPING_START 286
%token KOI_SCRIPT_TOKEN_TYPE_GROUPING_END 287
%token KOI_SCRIPT_TOKEN_TYPE_BODY_START 288
%token KOI_SCRIPT_TOKEN_TYPE_BODY_END 289
%token KOI_SCRIPT_TOKEN_TYPE_GENERIC_START 290
%token KOI_SCRIPT_TOKEN_TYPE_GENERIC_END 291
%token KOI_SCRIPT_TOKEN_TYPE_OPERATOR_MEMBER_ACCESS 292
%token KOI_SCRIPT_TOKEN_TYPE_OPERATOR_INHERITANCE 293
%token KOI_SCRIPT_TOKEN_TYPE_OPERATOR_SCOPE 294
%token KOI_SCRIPT_TOKEN_TYPE_OPERATOR_REFERENCE 295
%token KOI_SCRIPT_TOKEN_TYPE_OPERATOR_RETURN 296
%token KOI_SCRIPT_TOKEN_TYPE_COMMENT 297
%token KOI_SCRIPT_TOKEN_TYPE_DOCUMENTATION_COMMENT 298
%token KOI_SCRIPT_TOKEN_TYPE_WHITE_SPACE 299
%token KOI_SCRIPT_TOKEN_TYPE_NEW_LINE 300
%token KOI_SCRIPT_TOKEN_TYPE_EOF 301
%token KOI_SCRIPT_TOKEN_TYPE_SIZE 302

%%

ClassTypes : ClassType
    | ClassTypes ClassType
    ;

ClassType : KOI_SCRIPT_TOKEN_TYPE_CLASS_OBJECT { printf("%s: %d", yytext, $1); }
    | KOI_SCRIPT_TOKEN_TYPE_CLASS_BOOL { printf("%s: %d", yytext, $1); }
    | KOI_SCRIPT_TOKEN_TYPE_CLASS_CHAR { printf("%s: %d", yytext, $1); }
    | KOI_SCRIPT_TOKEN_TYPE_CLASS_INT { printf("%s: %d", yytext, $1); }
    | KOI_SCRIPT_TOKEN_TYPE_CLASS_UINT { printf("%s: %d", yytext, $1); }
    | KOI_SCRIPT_TOKEN_TYPE_CLASS_FLOAT { printf("%s: %d", yytext, $1); }
    | KOI_SCRIPT_TOKEN_TYPE_CLASS_UFLOAT { printf("%s: %d", yytext, $1); }
    | KOI_SCRIPT_TOKEN_TYPE_CLASS_STRING { printf("%s: %d", yytext, $1); }
    | KOI_SCRIPT_TOKEN_TYPE_CLASS_TYPE_NAME { printf("%s: %d", yytext, $1); }
    ;

%%

void yyerror(char* msg) {
  fprintf(stderr, msg);
}